sonar.projectKey=sqp_19046a77d97df496f465ebe8a483c3fa0c887166

sonar.projectName=APP1
sonar.projectVersion=1.0

# 👇 Include all folders
sonar.sources=frontend,Backend1,Backend2,Backend3

sonar.sourceEncoding=UTF-8
